deployments:
  cohere_platform:
    api_key: YOUR_COHERE_API_KEY
  sagemaker:
    access_key: YOUR_AWS_ACCESS_KEY
    secret_key: YOUR_AWS_SECRET_KEY
    session_token: YOUR_AWS_SESSION_TOKEN
  azure:
    api_key: YOUR_AZURE_API_KEY
  bedrock:
    access_key: YOUR_BEDROCK_ACCESS_KEY
    secret_key: YOUR_BEDROCK_SECRET_KEY
    session_token: YOUR_BEDROCK_SESSION_TOKEN
database:
  # Migrate access token, used to authenticate requests to the migrate endpoint.
  # Generate using a secure random string generator
  migrate_token: YOUR_MIGRATE_TOKEN
tools:
  tavily:
    api_key: YOUR_TAVILY_API_KEY
  wolfram_alpha:
    app_id: YOUR_WOLFRAM_APP_ID
  google_drive:
    client_id: YOUR_GOOGLE_DRIVE_CLIENT_ID
    client_secret: YOUR_GOOGLE_DRIVE_CLIENT_SECRET
    developer_key: YOUR_GOOGLE_DRIVE_DEVELOPER_KEY
  tavily_web_search:
    api_key: YOUR_TAVILY_SEARCH_API_KEY
  brave_web_search:
    api_key: YOUR_BRAVE_API_KEY
  google_web_search:
    api_key: YOUR_GOOGLE_SEARCH_API_KEY
    cse_id: YOUR_GOOGLE_CSE_ID
  slack:
    client_id: YOUR_SLACK_CLIENT_ID
    client_secret: YOUR_SLACK_CLIENT_SECRET
  gmail:
    client_id: YOUR_GMAIL_CLIENT_ID
    client_secret: YOUR_GMAIL_CLIENT_SECRET
  github:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET
  sharepoint:
    client_id: YOUR_SHAREPOINT_CLIENT_ID
    client_secret: YOUR_SHAREPOINT_CLIENT_SECRET
auth:
  secret_key: YOUR_AUTH_SECRET_KEY
  google_oauth:
    client_id: YOUR_GOOGLE_OAUTH_CLIENT_ID
    client_secret: YOUR_GOOGLE_OAUTH_CLIENT_SECRET
  scim:
    username: YOUR_SCIM_USERNAME
    password: YOUR_SCIM_PASSWORD
  oidc:
    client_id: YOUR_OIDC_CLIENT_ID
    client_secret: YOUR_OIDC_CLIENT_SECRET
    well_known_endpoint: YOUR_OIDC_WELL_KNOWN_ENDPOINT
google_cloud:
  api_key: YOUR_GOOGLE_CLOUD_API_KEY
